# Generated by Django 4.2.6 on 2023-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='s3_url',
            field=models.URLField(blank=True),
        ),
    ]
