# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++ gcc

# Install dependencies for both proxy server and client
COPY package.json yarn.lock ./
RUN yarn install

# Copy proxy server files
COPY . .

# Install client dependencies
WORKDIR /app/client
COPY client/package.json client/yarn.lock ./
RUN yarn install

# Copy client files
COPY client/ .

# Set back to root directory
WORKDIR /app

# Add node_modules/.bin to PATH
ENV PATH /app/node_modules/.bin:$PATH
ENV PATH /app/client/node_modules/.bin:$PATH

# Expose ports for both proxy server and client
EXPOSE 5000 3000

# Start both servers in development mode
CMD ["sh", "-c", "yarn start & cd client && yarn start"]
