# Generated by Django 4.0.5 on 2024-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='transcriptions_left',
            field=models.IntegerField(default=5),
        ),
    ]
