# Generated by Django 4.0.5 on 2024-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_transcriptions_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='transcriptions_done',
            field=models.IntegerField(default=0),
        ),
    ]
