# Generated by Django 4.0.5 on 2024-02-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_options_alter_file_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='s3_url',
        ),
        migrations.AddField(
            model_name='file',
            name='s3_key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
